#!/bin/bash
#==HEADER==
#Name:cylon-deb 
#Written by Gavin lyons 
#Software repo: https://github.com/gavinlyonsrepo/cylon_deb

#==GLOBAL VARIABLES SETUP==

#colours for printf
RED=$(printf "\033[31;1m")
GREEN=$(printf "\033[32;1m")
YELLOW=$(printf "\033[33;1m")
BLUE=$(printf "\033[36;1m")
HL=$(printf "\033[42;1m")
NORMAL=$(printf "\033[0m") 

#prompt for select menus
PS3="${BLUE}By your command:${NORMAL}"

#set the path for the program output path DEST3
#if environmental variable CYLONDEST exists set it to DEST3
#and make the path for dest3
if [ -z "${CYLONDEST}" ]
then 
	#default path for program output
	DEST3="$HOME/Documents/cylondeb/"
else 
	DEST3="$CYLONDEST"
fi
mkdir -p "$DEST3"

DEST6="/usr/share/doc/cylondeb/" # readme
DEST7="/usr/lib/cylondeb/modules/" #lib modules
#DEST7="../modules/"  # Development path comment out for production

#==FUNCTIONS==
#Source the module files for the functions from the cylon library folder
#at /usr/lib/cylon/modules/* , Function syntax: nameFunc.
for MYFILE in "$DEST7"*;
do
	source "$MYFILE"
done


#==MAIN CODE==
#call check for user input options
checkinputFunc "$1"
clear
#Display opening screen title 
msgFunc line
msgFunc highlight "cylon-deb"
msgFunc norm "Debian based Linux Distro Maintenance Program"
msgFunc norm "$(dpkg -s cylondeb 2> /dev/null | grep Version)"
msgFunc norm "$(date +%T-%d-%a-Week%U-%b-%Y)"
msgFunc norm "Unix epoch time $(date +%s)"
msgFunc line

#loop until user exit 
while true; do
	#reset path to $HOME
	cd ~ || exitHandlerFunc DEST4
	#call the display main menu function
	DisplayFunc
done
#== END ==
